version: '2.1'
services:
    reverse_proxy:
        container_name: buck_reverse_proxy
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            server:
                condition: service_healthy
        volumes:
            - certificates:/etc/nginx/certs/
            - manager-certificates:/etc/nginx/certs/manager/
            - cert-auth:/etc/nginx/certs/ca/
            - ./volumes/reverse_proxy/config/server.conf:/etc/nginx/conf.d/server.conf
            - ./volumes/reverse_proxy/certs:/etc/nginx/certs/buckutt/

    database:
        container_name: buck_database
        image: rethinkdb
        expose:
            - "28015"
            - "29015"
        ports:
            - "8080:8080"
        volumes:
            - ./volumes/database/data:/data
        healthcheck:
            test: "ls /data/rethinkdb_data/tmp/"
            timeout: 5s
            interval: 5s
            retries: 10

    server:
        container_name: buck_server
        image: buckless/server
        expose:
            - "3000"
        depends_on:
            database:
                condition: service_healthy
        environment:
            NODE_ENV: production
            SERVER_PROTOCOL: http
        volumes:
            - ./volumes/server/config:/usr/src/buckless-server/config/profiles
            - ./volumes/server/admin-certificate:/usr/src/buckless-server/ssl/certificates/admin
            - ./volumes/server/log:/usr/src/buckless-server/log
            - cert-auth:/usr/src/buckless-server/ssl/certificates/ca
            - certificates:/usr/src/buckless-server/ssl/certificates/server
            - manager-certificates:/usr/src/buckless-server/ssl/certificates/manager
        healthcheck:
            test: "ls /usr/src/buckless-server/ready.lock"
            timeout: 5s
            interval: 5s
            retries: 10

    admin:
        container_name: buck_admin
        image: buckless/admin
        build: ./images/admin
        expose:
            - "8082"
        environment:
            NODE_ENV: production

    manager:
        container_name: buck_manager
        image: buckless/manager
        build: ./images/manager
        expose:
            - "8083"
        depends_on:
            server:
                condition: service_healthy
        environment:
            NODE_ENV: production
            API_HOST: reverse_proxy
            API_PORT: 443
        volumes:
            - ./volumes/manager/icons:/usr/src/buckless-manager/public/images

    images:
        container_name: buck_images
        image: buckless/image-server
        expose:
            - "3400"
        volumes:
            - ./volumes/image-server/images:/usr/src/buckless-image-server/images
        environment:
            NODE_ENV: production

volumes:
    certificates:
        driver: local
    manager-certificates:
        driver: local
    cert-auth:
        driver: local
