version: '2.1'
services:
    nginx_service:
        build: ./nginx-reverse-proxy
        container_name: nginx_server
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            server:
                condition: service_healthy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certificates:/etc/nginx/certs/
            - cert-auth:/etc/nginx/certs/ca/

    database:
        image: rethinkdb
        expose:
            - "28015"
            - "29015"
        ports:
            - "8080:8080"
        volumes:
            - ./data:/data
        healthcheck:
            test: "ls /data/rethinkdb_data/tmp/"
            timeout: 5s
            interval: 5s
            retries: 10

    server:
        image: buckless/server
        expose:
            - "3000"
        depends_on:
            database:
                condition: service_healthy
        environment:
            NODE_ENV: prod
        volumes:
            - ./admin:/usr/src/buckless-server/ssl/certificates/admin
            - cert-auth:/usr/src/buckless-server/ssl/certificates/ca
            - certificates:/usr/src/buckless-server/ssl/certificates/server
            - manager-certificates:/usr/src/buckless-server/ssl/certificates/manager
            - ./log/server:/usr/src/buckless-server/log
        healthcheck:
            test: "ls /usr/src/buckless-server/ready.lock"
            timeout: 5s
            interval: 5s
            retries: 10

    client:
        image: buckless/client
        expose:
            - "8081"
        environment:
            VIRTUAL_HOST: ~^client\..+\.inst.buckless\.com
            VIRTUAL_PROTO: http

    admin:
        image: buckless/admin
        expose:
            - "8082"
        environment:
            VIRTUAL_HOST: ~^admin\..+\.inst.buckless\.com
            VIRTUAL_PROTO: http

    manager:
        image: buckless/manager
        expose:
            - "8083"
        environment:
            VIRTUAL_HOST: ~^[^\.]+\.inst.buckless\.com
            VIRTUAL_PROTO: http
        volumes:
            - manager-certificates:/usr/src/buckless-manager/ssl:ro

volumes:
    certificates:
        driver: local
    manager-certificates:
        driver: local
    cert-auth:
        driver: local
