version: '2.1'
services:
    nginx:
        container_name: buck_reverse_proxy
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            server:
                condition: service_healthy
        volumes:
            - certificates:/etc/nginx/certs/
            - cert-auth:/etc/nginx/certs/ca/
            - ./images/nginx/server.conf:/etc/nginx/conf.d/server.conf

    database:
        container_name: buck_database
        image: rethinkdb
        expose:
            - "28015"
            - "29015"
        ports:
            - "8080:8080"
        volumes:
            - ./volumes/database/data:/data
        healthcheck:
            test: "ls /data/rethinkdb_data/tmp/"
            timeout: 5s
            interval: 5s
            retries: 10

    server:
        container_name: buck_server
        build: ./images/buckless-server
        image: buckless/server
        expose:
            - "3000"
        depends_on:
            database:
                condition: service_healthy
        environment:
            NODE_ENV: production
        volumes:
            - ./volumes/server/admin-certificate:/usr/src/buckless-server/ssl/certificates/admin
            - ./volumes/server/log:/usr/src/buckless-server/log
            - cert-auth:/usr/src/buckless-server/ssl/certificates/ca
            - certificates:/usr/src/buckless-server/ssl/certificates/server
            - manager-certificates:/usr/src/buckless-server/ssl/certificates/manager
        healthcheck:
            test: "ls /usr/src/buckless-server/ready.lock"
            timeout: 5s
            interval: 5s
            retries: 10

    admin:
        container_name: buck_admin
        build: ./images/buckless-admin
        image: buckless/admin
        expose:
            - "8082"
        environment:
            NODE_ENV: production

    manager:
        container_name: buck_manager
        build: ./images/buckless-manager
        image: buckless/manager
        expose:
            - "8083"
        depends_on:
            server:
                condition: service_healthy
        environment:
            NODE_ENV: production
        volumes:
            - manager-certificates:/usr/src/buckless-manager/ssl:ro

volumes:
    certificates:
        driver: local
    manager-certificates:
        driver: local
    cert-auth:
        driver: local
