version: '2'
services:
    database:
        image: rethinkdb
        expose:
            - "28015"
            - "29015"
        ports:
            - "8080:8080"
        volumes:
            - ./data:/data

    server:
        image: buckless/server
        ports:
            - "3000:3000"
        expose:
            - "3000"
        depends_on:
            - database
        environment:
            NODE_ENV: prod
        volumes:
            - ./certificates:/usr/src/buckless-server/ssl/certificates

    client:
        image: buckless/client
        ports:
            - "8081:8081"

    admin:
        image: buckless/admin
        ports:
            - "8082:8082"

    manager:
        image: buckless/manager
        ports:
            - "8083:8083"
