version: '2.1'
services:
    server:
        volumes:
            - ../server/src:/usr/src/buckless-server/src
        command: ["npm", "run", "watch"]

    admin:
        volumes:
            - ../admin/src:/usr/src/buckless-admin/src
        command: ["npm", "run", "dev"]

    manager:
        volumes:
            - ../manager/src:/usr/src/buckless-manager/src
